Person15.04.2021
MihailLapanik/PersonBase pull request #2
Opened 2021-04-18 22:26 UTC by MihailLapanik

2021-04-20 11:14 UTC, Vlasik-Henadzi commented on src/main/java/Person/GeneratePerson.java
> +    private final int LIMIT;
можно в основной программе его проинициализировать в  public static final  переменной и тут не дублировать

2021-04-20 11:15 UTC, Vlasik-Henadzi commented on src/main/java/Person/GeneratePerson.java
> +                .limit(LIMIT)
Program.LIMIT

2021-04-20 11:17 UTC, Vlasik-Henadzi commented on src/main/java/Person/Program.java
> +        WorkWithBase base = new WorkWithBase();
WriteAndRead base = new WorkWithBase();

2021-04-20 11:19 UTC, Vlasik-Henadzi requested changes

2021-04-20 11:19 UTC, Vlasik-Henadzi commented on src/main/java/Person/WorkWithBase.java
> +            try (Connection myConnection = DriverManager.getConnection(URL, user, password)) {
тут лучше наооборот открыть одно соединение и внем пробежатья по всем Person и сохранить.
Если делать так до для 100 Person  будет создано и закрыто 100 соединений.
Отрыть соединение с базой - это дорогая по времени операция.

2021-04-25 17:32 UTC, MihailLapanik commented on src/main/java/Person/GeneratePerson.java
> +    private final int LIMIT;
исправил

2021-04-25 17:32 UTC, MihailLapanik commented on src/main/java/Person/GeneratePerson.java
> +                .limit(LIMIT)
исправил

2021-04-25 17:33 UTC, MihailLapanik commented on src/main/java/Person/Program.java
> +        WorkWithBase base = new WorkWithBase();
исправил

2021-04-25 17:33 UTC, MihailLapanik commented on src/main/java/Person/WorkWithBase.java
> +            try (Connection myConnection = DriverManager.getConnection(URL, user, password)) {
исправил

2021-05-19 13:46 UTC, merged